spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/hotel?currentSchema=test_database'
    username: postgres
    password: oybek
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update